import {
  AlertTriangle,
  Archive,
  ArrowRight,
  Award,
  BadgeCheck,
  Ban,
  BarChart3,
  Bell,
  BookOpen,
  Bookmark,
  Building2,
  Calendar,
  CheckCircle2,
  ChevronRight,
  ClipboardList,
  Clock,
  Compass,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  FileCheck,
  FileText,
  Filter,
  Flag,
  Folder,
  Globe,
  GraduationCap,
  HandCoins,
  Handshake,
  Headphones,
  HelpCircle,
  History,
  Home,
  Image,
  Inbox,
  Info,
  KeyRound,
  Languages,
  LayoutDashboard,
  LifeBuoy,
  Lightbulb,
  Link,
  ListChecks,
  ListTree,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MapPin,
  Megaphone,
  Menu,
  MessageSquare,
  Monitor,
  Newspaper,
  Notebook,
  Package,
  Pen,
  Phone,
  PieChart,
  Play,
  Plus,
  Printer,
  QrCode,
  Receipt,
  RefreshCw,
  Rocket,
  ScrollText,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Table,
  Tag,
  Timer,
  Trash2,
  Upload,
  User,
  UserPlus,
  Users,
  UsersRound,
  Video,
  Wallet,
  WifiOff,
  Wrench,
  XCircle,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import { type GuideIconKey } from '@fetrag/contracts'

/**
 * Icônes lucide associées aux clés d'icônes des guides (`guideIconKeys` de `@fetrag/contracts`).
 * Le type `Record<GuideIconKey, LucideIcon>` impose une entrée par clé : toute clé ajoutée aux
 * contrats sans icône ici fait échouer la compilation.
 */
export const guideIcons: Record<GuideIconKey, LucideIcon> = {
  'alert-triangle': AlertTriangle,
  archive: Archive,
  'arrow-right': ArrowRight,
  award: Award,
  'badge-check': BadgeCheck,
  ban: Ban,
  'bar-chart': BarChart3,
  bell: Bell,
  'book-open': BookOpen,
  bookmark: Bookmark,
  building: Building2,
  calendar: Calendar,
  'check-circle': CheckCircle2,
  'chevron-right': ChevronRight,
  'clipboard-list': ClipboardList,
  clock: Clock,
  compass: Compass,
  'credit-card': CreditCard,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'file-check': FileCheck,
  'file-text': FileText,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  globe: Globe,
  'graduation-cap': GraduationCap,
  'hand-coins': HandCoins,
  handshake: Handshake,
  headphones: Headphones,
  'help-circle': HelpCircle,
  history: History,
  home: Home,
  image: Image,
  inbox: Inbox,
  info: Info,
  'key-round': KeyRound,
  languages: Languages,
  'layout-dashboard': LayoutDashboard,
  'life-buoy': LifeBuoy,
  lightbulb: Lightbulb,
  link: Link,
  'list-checks': ListChecks,
  'list-tree': ListTree,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  'mail-check': MailCheck,
  'map-pin': MapPin,
  megaphone: Megaphone,
  menu: Menu,
  'message-square': MessageSquare,
  monitor: Monitor,
  newspaper: Newspaper,
  notebook: Notebook,
  package: Package,
  pen: Pen,
  phone: Phone,
  'pie-chart': PieChart,
  play: Play,
  plus: Plus,
  printer: Printer,
  'qr-code': QrCode,
  receipt: Receipt,
  refresh: RefreshCw,
  rocket: Rocket,
  'scroll-text': ScrollText,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shopping-cart': ShoppingCart,
  sliders: SlidersHorizontal,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  table: Table,
  tag: Tag,
  timer: Timer,
  trash: Trash2,
  upload: Upload,
  user: User,
  'user-plus': UserPlus,
  users: Users,
  'users-round': UsersRound,
  video: Video,
  wallet: Wallet,
  'wifi-off': WifiOff,
  wrench: Wrench,
  'x-circle': XCircle,
  zap: Zap,
}

/** Icône d'une clé, avec repli (`info`) pour une clé absente. */
export function guideIcon(key: GuideIconKey | undefined, fallback: LucideIcon = Info): LucideIcon {
  return key ? (guideIcons[key] ?? fallback) : fallback
}
